### ISSUE TITLE
Formatting ignored across single line wrap

### ISSUE THREAD

**Issue by patricktokeeffe** [benweet/stackedit#1040]
I'm copying and pasting from readme files containing lines hardwrapped for terminal display. I have disabled "GFM newlines" as remarked in #249:

> <kbd>#</kbd> &rarr; <kbd>Settings</kbd> &rarr; <kbd>Extensions</kbd> &rarr; <kbd>Markdown Extra</kbd> &rarr; &#x2610; GFM newlines

The problem is formatting is no longer recognized across the single-line-wrapping:

![image](https://cloud.githubusercontent.com/assets/1348834/20366441/f9419f28-abff-11e6-88a0-c096de86c792.png)

I would expect this result instead:

![image](https://cloud.githubusercontent.com/assets/1348834/20366891/fdf84fce-ac01-11e6-80e5-d020d6e93315.png)

**Comment by benweet** [comment]
Should be fixed in the v5 (https://stackedit.io/app). Please open a new ticket if it's not.

**Comment by patricktokeeffe** [comment]
Hi, pardon my delay. I confirm this still exists in v4 but is working properly in version 5. Thanks!
