### ISSUE TITLE
Multi Version Merge Problem

### ISSUE THREAD

**Issue by zzt93** [benweet/stackedit#1180]
I use stackedit both on working compute and on my own computer. In stackedit4, if there is a version diverge, stackedit will add some mark like git does. But in stackedit5, it seems it will automatically merge. But the conflict part will become a mess, like following:

```
te tat rapvertices rtrns an erte(trin Strin
```
Does this because I forget to close another compute's stackedit when I edit in current one? Any solution?

**Comment by ferdossi** [comment]
I have oftenly the same issue. It's very annoying as sometimes you just want just to have a quick look at a document but as soon as you open it, the messy merge has operated and you are completely screwed as you can't do any undo, a conflicting merge URL is impossible to recover. The only workaround is to go back to the last device where the you edited to document, cut immediately the connection to avoid any merge with the "bad merged" document and hope that nothing changed since.
Or login with a Gmail account and use the file history..

**Comment by benweet** [comment]
Should be fixed in v5.5.0.

**Comment by zzt93** [comment]
![image](https://user-images.githubusercontent.com/5842389/34906743-25fd75ae-f8ae-11e7-8eeb-62a650d5f8d2.png)

Thanks for your work. But, as the image show, the bug still exists.

**Comment by delbaredouard** [comment]
Hi. I use Stackedit 5.14 on a single computer, and sometimes it looks like two different versions of the same document have been merged. Do you think this issue is related to my documents being linked to two sync locations ("Google Drive app data" and "docs.google.com") ? Should I remove one ? By the way, what is Google Drive app data ? Is it a local or a remote location ?
