### ISSUE TITLE
Uncaught TypeError: Cannot set property 'comment' of undefined

### ISSUE THREAD

**Issue by Jesn** [benweet/stackedit#1311]
error  info:

Uncaught TypeError: Cannot set property 'comment' of undefined
    at Object.extend (prism.js:90)
    at Object.<anonymous> (prism.js:5384)
    at Object.<anonymous> (prism.js:7884)
    at __webpack_require__ (bootstrap 4821f47ec4e428c4e6c0:659)
    at fn (bootstrap 4821f47ec4e428c4e6c0:85)
    at Object.<anonymous> (app.js:86065)
    at __webpack_require__ (bootstrap 4821f47ec4e428c4e6c0:659)
    at fn (bootstrap 4821f47ec4e428c4e6c0:85)
    at Object.<anonymous> (app.js:85861)
    at __webpack_require__ (bootstrap 4821f47ec4e428c4e6c0:659)

**Comment by futurist** [comment]
+1, same from me

**Comment by Tarhyru** [comment]
+2, same from me
so,What should I do？

**Comment by benweet** [comment]
Did you get this on stackedit.io ? Can you share a markdown sample to reproduce the issue ?

**Comment by Tarhyru** [comment]
stackedit.io..Quick start ，I can run up
no error have report

**Comment by Tarhyru** [comment]
![img](https://s1.ax1x.com/2018/05/23/CWPg0S.png)

**Comment by benweet** [comment]
Can you try to reinstall your node_modules with npm v5?

**Comment by Tarhyru** [comment]
fine I run up,but i alawys use npm v 5.6.
so i speculate，it‘s Network link problem
because in other linux computer,I find the PhantomJS Downloads are always impossible to complete。
And again to execute install，the can't be download
Need rm node_modules and /tmp/PhantomJS。
other maybe before i use chineses path cause some error,This is very common
but I don't want to prove it
In any case thx

**Comment by WillsXiao** [comment]
+3, same problem for me

**Comment by Tarhyru** [comment]
楼上那个..这个问题已经解决了....
就两个可能
1、依赖安装不完全
2、文件目录有中文.

**Comment by ursulashan** [comment]
Upgrade npm to the latest version `npm i npm@latest -g` is work for me

**Comment by benweet** [comment]
Yes, upgrading to the latest npm and running `npm install` again should fix the problem.

**Comment by jaune162** [comment]
I upgrade my npm to the latest version(6.1.0).
Then remove `node_modules` folder and execute `npm install` to reinstall the dependency packages.
But the problem remains unresolved.

**Comment by jaune162** [comment]
问题找到了，这个不是npm版本的问题。而是`prismjs`的问题。由于package.json中配置的是`"prismjs": "^1.6.0"`，我这里下载包的时候直接下载了最新版`1.15.0`，而最新版本的`prismjs`有BUG，所以会一直报错（测试的`1.15.0`和`1.14.0`都有问题）。换成`1.9.0`版本就没有问题了(因为package-lock.json中是`1.9.0`)。

参加我提的这个issue，<https://github.com/PrismJS/prism/issues/1448>

英文比较渣，可能会有语法上的问题，凑合看吧。

**Comment by Jesn** [comment]
@jaune162   试过你的方法，改成1.9.0的版本然后就可以了

**Comment by woncode** [comment]
我的方法是：
1. 删除node_modules
2. 设置package.json的prismjs版本为1.9.0
3. 先手动安装prismjs：`npm install prismjs@1.9.0`
4. 安装其他依赖包：`npm install`
5. 启动成功：`npm start`

**Comment by cuongdaovan** [comment]
I still have this kind of problem

**Comment by TokugawaTakeshi** [comment]
Just finished the experiments with `"prismjs": "1.29.0"` (the newest one for Aug 2024).
Among below distributable `.js` files, only `prismjs/components/prism-tsx.js` causes `TypeError: Cannot set properties of undefined (setting 'comment')`.

```
import "prismjs/components/prism-typescript.js";
import "prismjs/components/prism-pug.js";
import "prismjs/components/prism-stylus.js";
import "prismjs/components/prism-yaml.js";
import "prismjs/components/prism-csharp.js";
import "prismjs/components/prism-tsx.js";
```
