### ISSUE TITLE
not equal sign renders incorrectly

### ISSUE THREAD

**Issue by zrwang** [benweet/stackedit#1460]
The not equal sign cannot render correctly in StackEdit.
The following code
```
$\ne$, $\neq$
```
gives the result shown in the picture below.
![Screen Shot](https://user-images.githubusercontent.com/5280342/54738923-261ac180-4bf1-11e9-8cc1-b485a34900b4.png)

**Comment by joedmck** [comment]
I also experienced this

**Comment by metruzanca** [comment]
As did I. Hope it gets fixed.

**Comment by ursulashan** [comment]
Also, and didn't fix

**Comment by bet4a** [comment]
This bug occurs due to [an issue](https://github.com/KaTeX/KaTeX/issues/1842) with the KaTeX math typesetting library, which has since been fixed in https://github.com/KaTeX/KaTeX/pull/1852.

Resolving this should be as simple as bumping up StackEdit’s [KaTeX dependency](https://github.com/benweet/stackedit/blob/master/package.json#L41) to version `v0.10.1`, which includes the fix.

**Comment by jhugon61** [comment]
I was experiencing the same issue, and upgraded to KAtex 0.10.1. The fix seems to work for me in Chrome and Firefox, but I still experience the same issue with Safari 12.1 on OSX and iOS 12.2. Are others experiencing the same issue? I can reproduce this by pointing Safari to https://katex.org and typing: a \ne b in the interactive window. Any thoughts or suggestions?

**Comment by bet4a** [comment]
> I was experiencing the same issue, and upgraded to KAtex 0.10.1. The fix seems to work for me in Chrome and Firefox, but I still experience the same issue with Safari 12.1 on OSX and iOS 12.2. Are others experiencing the same issue? I can reproduce this by pointing Safari to https://katex.org and typing: a \ne b in the interactive window. Any thoughts or suggestions?

Seems you’re not alone… other Safari users are reporting similar problems at https://github.com/KaTeX/KaTeX/issues/1941. There’s a fix in the master branch of KaTeX (https://github.com/KaTeX/KaTeX/commit/ff5ebea681c0710805c32f62e7efe96c1b432938  )… which really just points the KaTeX font references to an updated version of the KaTeX math fonts. Unfortunately there hasn’t been a KaTeX release since 0.10.1, which was before that fix was pushed.

I don’t have a Safari device to test on, but presumably if you monkey patch in the latest [KaTeX font files](https://github.com/KaTeX/katex-fonts/tree/master/fonts) (rather than the ones included as part of KaTeX 0.10.1), I *think* that should be sufficient to get things working in Safari…

**Comment by jhugon61** [comment]
Thanks for your helpful email. I am not sure how to patch together a library as you suggested, but will give it a try following your instructions. In the meantime, I am hoping some kind soul with the skill to do so will put together a 0.14.2 release soon.

All the best,
~~~~~~~~~~~~~~~~~~~~~
Jacques Hugon
jacques.hugon@gmail.com
~~~~~~~~~~~~~~~~~~~~~

**Comment by jhugon61** [comment]
Meant 0.10.2, sorry.
~~~~~~~~~~~~~~~~~~~~~
Jacques Hugon
jacques.hugon@gmail.com
~~~~~~~~~~~~~~~~~~~~~

**Comment by benweet** [comment]
Fixed with v5.14.10.
