### ISSUE TITLE
[Update request] Bump Katex from ^v0.10.2 to ^v0.11.1.

### ISSUE THREAD

**Issue by ericlincc** [benweet/stackedit#1591]
Latest version: 0.11.1.

https://www.npmjs.com/package/katex

**Comment by ariel-co** [comment]
FWIW, it includes KaTeX/KaTeX#2053 which allows \includegraphics

**Comment by benweet** [comment]
Fixed with v5.14.10.

**Comment by DaMatrix** [comment]
Running v5.14.10, and `\includegraphics` still doesn't work (shows up in red).
