### ISSUE TITLE
Google sign in issue

### ISSUE THREAD

**Issue by amitguptagwl** [benweet/stackedit#1717]
Authorization error in google signin

Error 400: invalid_request
Missing required parameter: client_id

**Comment by jshum** [comment]
![Uploading Screen Shot 2021-04-08 at 3.55.28 PM.png…]()

**Comment by mantielero** [comment]
I am facing the same problem when trying to get access to stackedit files that I created in Google Drive.

It seems related with [OAuth 2.0](https://developers.google.com/identity/protocols/oauth2).

**Comment by amitguptagwl** [comment]
The issue seems resolved now. But Now I have shifted away from sackedit

**Comment by mantielero** [comment]
I still face the same problem. 

P.S.: It is really sad to hear that Amit. Stackedit is amazing. Will be somebody taking over the development?
